set(arguments -S "${UNIMEMORY_SOURCE}/tests/package" -B "${TEST_BINARY}"
    -G "${TEST_GENERATOR}" "-DUNIMEMORY_SOURCE=${UNIMEMORY_SOURCE}"
    "-DSCENARIO=${SCENARIO}" "-DLOOKUP_MODE=${LOOKUP_MODE}" "-DNM_FIXTURE=${NM_FIXTURE}")
if(INSTALLED_PACKAGE)
    list(APPEND arguments "-DINSTALLED_PACKAGE=${INSTALLED_PACKAGE}" "-Dmimalloc_DIR=${mimalloc_DIR}")
endif()
if(TEST_PLATFORM)
    list(APPEND arguments -A "${TEST_PLATFORM}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" ${arguments}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${TEST_BINARY}/lookup.log" "${output}\n${error}")
if(LOOKUP_MODE STREQUAL "source" OR
   (LOOKUP_MODE STREQUAL "required" AND NOT SCENARIO MATCHES "^(valid|debug_fallback)$"))
    if(SCENARIO STREQUAL "missing_include")
        set(reason "jemalloc/jemalloc[.]h")
    elseif(SCENARIO STREQUAL "missing_library")
        set(reason "UNIMEMORY_JEMALLOC_RELEASE_LIBRARY|jemalloc library")
    elseif(SCENARIO STREQUAL "missing_nm")
        set(reason "target toolchain's nm")
    elseif(SCENARIO MATCHES "^nm_")
        set(reason "Cannot inspect jemalloc symbols")
    else()
        set(reason "replaces global C[+][+] new/delete")
    endif()
    if(result EQUAL 0 OR NOT "${output}\n${error}" MATCHES "${reason}")
        message(FATAL_ERROR "Expected dependency diagnostic and configure failure:\n${output}\n${error}")
    endif()
elseif(NOT result EQUAL 0)
    message(FATAL_ERROR "Package lookup did not honor its optional/valid contract:\n${output}\n${error}")
endif()
