function(unimemory_check_installed_requests)
    cmake_parse_arguments(ARG "" "PACKAGE_DIR;BINARY_DIR;BACKEND;STATISTICS;CHECKS" "" ${ARGN})
    foreach(required IN ITEMS PACKAGE_DIR BINARY_DIR BACKEND STATISTICS CHECKS)
        if(NOT DEFINED ARG_${required} OR ARG_${required} STREQUAL "")
            message(FATAL_ERROR "Installed request checks require ${required}")
        endif()
    endforeach()
    set(_fixture "${CMAKE_CURRENT_FUNCTION_LIST_DIR}")
    set(_generator)
    if(CMAKE_GENERATOR)
        list(APPEND _generator -G "${CMAKE_GENERATOR}")
    endif()
    if(CMAKE_GENERATOR_PLATFORM)
        list(APPEND _generator -A "${CMAKE_GENERATOR_PLATFORM}")
    endif()
    if(CMAKE_GENERATOR_TOOLSET)
        list(APPEND _generator -T "${CMAKE_GENERATOR_TOOLSET}")
    endif()
    file(MAKE_DIRECTORY "${ARG_BINARY_DIR}")
    foreach(profile IN ITEMS BACKEND STATISTICS CHECKS)
        set(_backend "${ARG_BACKEND}")
        set(_statistics "${ARG_STATISTICS}")
        set(_checks "${ARG_CHECKS}")
        if(profile STREQUAL "BACKEND")
            if(ARG_BACKEND STREQUAL "standard")
                set(_backend mimalloc)
            else()
                set(_backend standard)
            endif()
            set(_reason "backend differs")
        elseif(profile STREQUAL "STATISTICS")
            if(ARG_STATISTICS STREQUAL "ON")
                set(_statistics OFF)
            else()
                set(_statistics ON)
            endif()
            set(_reason "statistics differ")
        else()
            if(ARG_CHECKS STREQUAL "ON")
                set(_checks OFF)
            else()
                set(_checks ON)
            endif()
            set(_reason "CHECKS policy differs")
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" -S "${_fixture}" -B "${ARG_BINARY_DIR}/${profile}"
            ${_generator} "-DUniMemory_DIR=${ARG_PACKAGE_DIR}"
            "-DUNIMEMORY_BACKEND=${_backend}" "-DUNIMEMORY_STATISTICS=${_statistics}" "-DUNIMEMORY_CHECKS=${_checks}"
            RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
        file(WRITE "${ARG_BINARY_DIR}/${profile}.log" "${output}\n${error}")
        if(status EQUAL 0 OR NOT "${output}\n${error}" MATCHES "${_reason}")
            message(FATAL_ERROR "Installed ${profile} request was accepted or failed for another reason:\n${output}\n${error}")
        endif()
    endforeach()
endfunction()
