option(UNIMEMORY_DIAGNOSTIC_IPO "Enable IPO only in this controlled diagnostic build" OFF)
option(UNIMEMORY_DIAGNOSTIC_PIC "Build diagnostic consumers with PIC" ON)
option(UNIMEMORY_DIAGNOSTIC_ADAPTER_EXTENSIONS "Keep GNU extensions in diagnostic adapter controls" ON)
option(UNIMEMORY_DIAGNOSTIC_ALIGN_LOOPS "Align GNU diagnostic loops to 64 bytes" OFF)
set_property(TARGET UniMemory PROPERTY INTERFACE_POSITION_INDEPENDENT_CODE ${UNIMEMORY_DIAGNOSTIC_PIC})
add_library(UniMemoryDiagnosticAdapters STATIC benchmarks/diagnostics/adapters.cpp)
set_property(TARGET UniMemoryDiagnosticAdapters PROPERTY CXX_EXTENSIONS ${UNIMEMORY_DIAGNOSTIC_ADAPTER_EXTENSIONS})
add_executable(UniMemoryDiagnostic
    benchmarks/diagnostics/main.cpp
    benchmarks/diagnostics/hotpath.cpp
    benchmarks/diagnostics/statistics.cpp
    benchmarks/diagnostics/backend.cpp
    benchmarks/diagnostics/api.cpp)
foreach(probe IN ITEMS UniMemoryDiagnosticAdapters UniMemoryDiagnostic)
    target_compile_features(${probe} PRIVATE cxx_std_20)
    target_link_libraries(${probe} PRIVATE UniMemory::UniMemory Threads::Threads)
    if(UNIMEMORY_WITH_MIMALLOC)
        target_compile_definitions(${probe} PRIVATE UNIMEMORY_BENCH_MIMALLOC UNIMEMORY_WITH_MIMALLOC)
        target_include_directories(${probe} PRIVATE "${UNIMEMORY_MIMALLOC_INCLUDE_DIR}")
        target_link_libraries(${probe} PRIVATE ${UNIMEMORY_MIMALLOC_TARGET})
    endif()
    if(UNIMEMORY_WITH_JEMALLOC)
        target_compile_definitions(${probe} PRIVATE UNIMEMORY_BENCH_JEMALLOC UNIMEMORY_WITH_JEMALLOC)
        target_link_libraries(${probe} PRIVATE unimemory_jemalloc)
    endif()
endforeach()
if(UNIMEMORY_DIAGNOSTIC_ALIGN_LOOPS)
    if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        message(FATAL_ERROR "The loop-placement control is GNU-only")
    endif()
    target_compile_options(UniMemoryDiagnostic PRIVATE -falign-loops=64)
endif()
target_link_libraries(UniMemoryDiagnostic PRIVATE UniMemoryDiagnosticAdapters ${CMAKE_DL_LIBS})
if(WIN32)
    target_link_libraries(UniMemoryDiagnostic PRIVATE psapi)
    target_link_options(UniMemoryDiagnostic PRIVATE /MAP)
endif()
if(UNIMEMORY_DIAGNOSTIC_IPO)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT supported OUTPUT explanation LANGUAGES CXX)
    if(NOT supported)
        message(FATAL_ERROR "Requested diagnostic IPO unsupported: ${explanation}")
    endif()
    foreach(probe IN ITEMS UniMemoryDiagnosticAdapters UniMemoryDiagnostic)
        set_property(TARGET ${probe} PROPERTY INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)
    endforeach()

endif()
file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/diagnostic-build-$<CONFIG>.txt" CONTENT
    "compiler=${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}\nconfiguration=$<CONFIG>\ncore=header-only\nbackend=${UNIMEMORY_BACKEND}\nstatistics=${UNIMEMORY_STATISTICS}\nchecks=${UNIMEMORY_CHECKS}\nipo=${UNIMEMORY_DIAGNOSTIC_IPO}\npic=${UNIMEMORY_DIAGNOSTIC_PIC}\nadapter_extensions=${UNIMEMORY_DIAGNOSTIC_ADAPTER_EXTENSIONS}\nalign_loops=${UNIMEMORY_DIAGNOSTIC_ALIGN_LOOPS}\nflags=${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELEASE}\n")
