option(UNIMEMORY_DIAGNOSTIC_IPO "Enable IPO only in this controlled diagnostic build" OFF)
option(UNIMEMORY_DIAGNOSTIC_PIC "Keep UniMemory PIC in this controlled diagnostic build" ON)
option(UNIMEMORY_DIAGNOSTIC_ADAPTER_EXTENSIONS "Keep GNU extensions in diagnostic adapter controls" ON)
option(UNIMEMORY_DIAGNOSTIC_ALIGN_LOOPS "Align GNU diagnostic loops to 64 bytes" OFF)
set(UNIMEMORY_DIAGNOSTIC_EXPORTS_FILE "" CACHE FILEPATH "Plain-object export list for the MSVC shared IPO experiment")
set_target_properties(UniMemory PROPERTIES POSITION_INDEPENDENT_CODE ${UNIMEMORY_DIAGNOSTIC_PIC})
add_library(UniMemoryDiagnosticAdapters STATIC benchmarks/diagnostics/adapters.cpp)
set_property(TARGET UniMemoryDiagnosticAdapters PROPERTY CXX_EXTENSIONS ${UNIMEMORY_DIAGNOSTIC_ADAPTER_EXTENSIONS})
add_executable(UniMemoryDiagnostic
    benchmarks/diagnostics/main.cpp
    benchmarks/diagnostics/hotpath.cpp
    benchmarks/diagnostics/statistics.cpp
    benchmarks/diagnostics/backend.cpp
    benchmarks/diagnostics/api.cpp)
foreach(probe IN ITEMS UniMemoryDiagnosticAdapters UniMemoryDiagnostic)
    target_compile_features(${probe} PRIVATE cxx_std_20)
    target_link_libraries(${probe} PRIVATE UniMemory::UniMemory Threads::Threads)
    if(UNIMEMORY_WITH_MIMALLOC)
        target_compile_definitions(${probe} PRIVATE UNIMEMORY_BENCH_MIMALLOC UNIMEMORY_WITH_MIMALLOC)
        target_include_directories(${probe} PRIVATE "${UNIMEMORY_MIMALLOC_INCLUDE_DIR}")
        target_link_libraries(${probe} PRIVATE ${UNIMEMORY_MIMALLOC_TARGET})
    endif()
    if(UNIMEMORY_WITH_JEMALLOC)
        target_compile_definitions(${probe} PRIVATE UNIMEMORY_BENCH_JEMALLOC UNIMEMORY_WITH_JEMALLOC)
        target_link_libraries(${probe} PRIVATE unimemory_jemalloc)
    endif()
endforeach()
if(UNIMEMORY_DIAGNOSTIC_ALIGN_LOOPS)
    if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        message(FATAL_ERROR "The loop-placement control is GNU-only")
    endif()
    target_compile_options(UniMemoryDiagnostic PRIVATE -falign-loops=64)
endif()
target_link_libraries(UniMemoryDiagnostic PRIVATE UniMemoryDiagnosticAdapters ${CMAKE_DL_LIBS})
if(WIN32)
    target_link_libraries(UniMemoryDiagnostic PRIVATE psapi)
    target_link_options(UniMemoryDiagnostic PRIVATE /MAP)
    if(BUILD_SHARED_LIBS)
        target_link_options(UniMemory PRIVATE /MAP)
    endif()
endif()
if(UNIMEMORY_DIAGNOSTIC_IPO)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT supported OUTPUT explanation LANGUAGES CXX)
    if(NOT supported)
        message(FATAL_ERROR "Requested diagnostic IPO unsupported: ${explanation}")
    endif()
    foreach(probe IN ITEMS UniMemory UniMemoryDiagnosticAdapters UniMemoryDiagnostic)
        set_property(TARGET ${probe} PROPERTY INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)
    endforeach()
    if(MSVC AND BUILD_SHARED_LIBS)
        if(NOT EXISTS "${UNIMEMORY_DIAGNOSTIC_EXPORTS_FILE}")
            message(FATAL_ERROR "MSVC shared IPO requires the matching non-IPO diagnostic export list")
        endif()
        # CMake's plain-COFF auto-export scanner cannot read /GL objects.
        # Reuse the exact ABI exported by the same source's non-IPO build.
        set_property(TARGET UniMemory PROPERTY WINDOWS_EXPORT_ALL_SYMBOLS OFF)
        target_sources(UniMemory PRIVATE "${UNIMEMORY_DIAGNOSTIC_EXPORTS_FILE}")
    endif()
endif()
file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/diagnostic-build-$<CONFIG>.txt" CONTENT
    "compiler=${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}\nconfiguration=$<CONFIG>\nshared=${BUILD_SHARED_LIBS}\nipo=${UNIMEMORY_DIAGNOSTIC_IPO}\npic=${UNIMEMORY_DIAGNOSTIC_PIC}\nadapter_extensions=${UNIMEMORY_DIAGNOSTIC_ADAPTER_EXTENSIONS}\nalign_loops=${UNIMEMORY_DIAGNOSTIC_ALIGN_LOOPS}\nflags=${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELEASE}\n")
